services:
  node-server:
    build:
      context: .
    image: "test-app:latest"
    ports:
      - "8000:8000"
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  grafana-server:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
  loki-server:
    image: grafana/loki
    ports:
      - 3100:3100