services:
  web:
    build:
      context: .
    image: "maainul/test-app:latest"
    ports:
      - "8000:8000"
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml
